apiVersion: apps/v1
kind: Deployment
metadata:
  name: swimlane
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swimlane
  template:
    metadata:
      labels:
        app: swimlane
    spec:
      containers:
        - name: app
          image: mylucidreality/swimlane
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URL
              value: mongodb://my-mongodb-0.database:27017
          imagePullPolicy: Always
